# Generated by Django 3.1.1 on 2020-11-22 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='Image',
            field=models.ImageField(upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='file',
            name='Name',
            field=models.CharField(max_length=100),
        ),
    ]
